name: CI

on: 
  push:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Hello world
      run: echo Hello, world!
      
  release:
    if: github.event_name == 'release'
    needs: [build]

    runs-on: ubuntu-latest
    
    steps:
      - name: Hello release
        run: Hello Release!
