name: Delete old pacakges

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: rubengees/delete-old-packages@master
      with:
        dry-run: true
        version: "1.0.0"
        names: test
