name: Delete old pacakges

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: smartsquaregmbh/delete-old-packages@v0.3.1
      with:
        version: "1.0.0"
        names: test
